### ISSUE TITLE
Security Issue: API key visible in repo

### ISSUE THREAD

**Issue by deadbits** [darryllane/Bluto#21]
@darryllane, Inside general.py you hard-coded your ipstack.com API key into the code. This represents a data leak and security issue for yourself. You should definitely remove this since anyone can now just use your key and burn your limits. I may or may not have tested it to ensure it is indeed an active key.

**Offending source code:**   
general.py#L137-L142

My suggestion (I do this for most projects) is that if you do need API keys, create a separate file for them that the user must fill out. For example, a JSON file with each service as the key and value as the API token and only read from that file when needed --- and of course, don't upload your own version of the API file ;-)

**Comment by darryllane** [comment]
Hi

Thanks for pointing it out however, this was intentional and by design. Im happy with the key being public, its a temporary fix till the version im deving is released

**Comment by deadbits** [comment]
Gotcha. ipstack.com keys are free, so if you're going for a way to let users have easy access once they dl your app it seems more likely those users will hit the "shared" API limit sooner versus creating their own token.

Just my two cents :)

Thanks for the quick reply

**Comment by darryllane** [comment]
You are correct sharing a key would hit limits sooner however, I monitor the utilisation of the application and know how many times its been used in the last 2 years. So any limits being hit will most likley be due to abuse of the key. When that happens I'll change the key, until the latest version im working on is deployed. Again thanks for pointing it out, it is appreciated 👍 :) Once the next Dev branch is released for beta would you mind doing some testing?
